# 이 파일은 black, isort, ruff 같은 파이썬 개발 도구들의
# 설정을 한 곳에서 관리하는 표준적인 방법입니다.

[tool.black]
# black의 한 줄 최대 길이를 설정합니다 (기본값).
line-length = 88
# 지원하는 파이썬 버전을 명시할 수 있습니다.
# target-version = ['py311', 'py312']

[tool.isort]
# ★★★ 가장 중요한 설정 ★★★
# isort의 정렬 프로필을 black과 완벽하게 호환되도록 설정합니다.
# 이 설정 하나로 두 도구의 충돌이 해결됩니다.
profile = "black"
line_length = 88

[tool.ruff]
# ruff도 black과 동일한 줄 길이를 사용하도록 설정합니다.
line-length = 88